In [7]:
import pandas as pd
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [12]:
df =  pd.read_excel("weather_data.xlsx" ,"Sheet1")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
df

In [13]:
weather_data = {
    "day": ["Monday", "Tuesday", "Wednesday"],
    "temperature": [30, 32, 28],
    "humidity": [70, 65, 80]
}

df = pd.DataFrame(weather_data)
print(df)

         day  temperature  humidity
0     Monday           30        70
1    Tuesday           32        65
2  Wednesday           28        80

In [14]:
import pandas as pd

weather_data = (
    ["Monday", "Tuesday", "Wednesday"],   # days
    [30, 32, 28],                        # temperature
    [70, 65, 80]                         # humidity
)

df = pd.DataFrame(weather_data).T
df.columns = ["day", "temperature", "humidity"]

print(df)

         day temperature humidity
0     Monday          30       70
1    Tuesday          32       65
2  Wednesday          28       80

In [15]:
weather_data = [
    {"day": "Monday", "temperature": 30, "humidity": 70},
    {"day": "Tuesday", "temperature": 32, "humidity": 65}
]

df = pd.DataFrame(weather_data)
df

       day  temperature  humidity
0   Monday           30        70
1  Tuesday           32        65